### ISSUE TITLE
Assert required redmine versions

### ISSUE THREAD

**Issue by matobaa** [matobaa/redmine_ld_rize#4]
plugins should assert required redmine versions with [Redmine::Plugin::requires_redmine](https://redmine.org/projects/redmine/repository/annotate/tags/4.2.2/lib/redmine/plugin.rb#L234).

see also: https://redmine.org/issues/2162

**Comment by matobaa** [comment]
- [ ] investigate and specify a minimum version of redmine that used widely
- [ ] decide a first and last version to support

**Comment by matobaa** [comment]
For earliest, as of now IMHO 3.3 is better; because of [a questionnaire in redmine tokyo #21](https://www.slideshare.net/naitoh1/redminetokyo21-questionnaire/4).
[A docker image if Redmine:3.3.0](https://hub.docker.com/_/redmine?tab=tags&name=3.3).

For latest, 4.2.3(stable) or 5.0(upcoming next major)

**Comment by matobaa** [comment]
tested with 3.3.0

**Comment by matobaa** [comment]
Failed with [trunk](https://www.redmine.org/projects/redmine/repository/revisions/21305). (5.0)

```
F, [2021-12-19T03:00:17.588599 #872] FATAL -- :   
TypeError (superclass mismatch for class LDRizeHooks):

plugins/redmine_ld_rize/init.rb:19:in `<top (required)>'
lib/redmine/plugin_loader.rb:31:in `load'
lib/redmine/plugin_loader.rb:31:in `run_initializer'
lib/redmine/plugin_loader.rb:108:in `each'
lib/redmine/plugin_loader.rb:108:in `block in load'
```

**Comment by matobaa** [comment]
passed with [trunk](https://www.redmine.org/projects/redmine/repository/revisions/21305) (5.0)
